### ISSUE TITLE
Support for custom hostname values

### ISSUE THREAD

**Issue by b-odonoghue** [Azure-Terraform/terraform-azurerm-virtual-machine#3]
By default when you build a host using this module it will take the name of the resource name. Though there are some cases where it would be great to be able to supply a custom hostname value. 

Looking both linux and windows support the `computer_name` value to set a custom hostname and as an option variable we can just set that value to the resource name if some custom name is not specified.

**Comment by jhisc** [comment]
Hi @b-odonoghue 

I've created a MR and example to address this request:
https://github.com/Azure-Terraform/terraform-azurerm-virtual-machine/pull/4/

Can you review and confirm it matches your requirements please?
Example - https://github.com/Azure-Terraform/terraform-azurerm-virtual-machine/blob/linux_hostname/examples/linux-custom-hostname/main.tf#L98

Thanks

**Comment by b-odonoghue** [comment]
@jhisc  this looks great thank you!

**Comment by jhisc** [comment]
Change has been tagged  v1.2.0
