### ISSUE TITLE
CustomData

### ISSUE THREAD

**Issue by wesleyemery** [Azure-Terraform/terraform-azurerm-virtual-machine#5]
Please add the ability to add CustomData script to the Virtual machine.

**Comment by wesleyemery** [comment]
# Linux Virtual Machine
resource "azurerm_linux_virtual_machine" "linux" {
  count = (var.kernel_type == "linux" ? 1 : 0)

  name                = local.virtual_machine_name
  location            = var.names.location
  resource_group_name = var.resource_group_name
  tags                = var.tags

  size                            = var.virtual_machine_size
  admin_username                  = local.admin_username
  admin_password                  = local.admin_password
  disable_password_authentication = false
  network_interface_ids           = [azurerm_network_interface.dynamic.id]

  source_image_id = var.custom_image_id
  custom_data = file[var.customdata]

  dynamic "source_image_reference" {
    for_each = var.custom_image_id == null ? ["no_custom_image_provided"] : []

    content {
      publisher = var.source_image_publisher
      offer     = var.source_image_offer
      sku       = var.source_image_sku
      version   = var.source_image_version
    }
  }

  os_disk {
    caching                   = var.operating_system_disk_cache
    storage_account_type      = var.operating_system_disk_type
    write_accelerator_enabled = var.operating_system_disk_write_accelerator
  }
}


# Windows
resource "azurerm_windows_virtual_machine" "windows" {
  count = (var.kernel_type == "windows" ? 1 : 0)

  name                = local.virtual_machine_name
  location            = var.names.location
  resource_group_name = var.resource_group_name
  tags                = merge(var.tags, { "name" : local.virtual_machine_name })


  size           = var.virtual_machine_size
  admin_username = local.admin_username
  admin_password = local.admin_password

  network_interface_ids = [azurerm_network_interface.dynamic.id]

  source_image_id = var.custom_image_id
  custom_data = file[var.customdata]

  dynamic "source_image_reference" {
    for_each = var.custom_image_id == null ? ["no_custom_image_provided"] : []

    content {
      publisher = var.source_image_publisher
      offer     = var.source_image_offer
      sku       = var.source_image_sku
      version   = var.source_image_version
    }
  }

  os_disk {
    caching                   = var.operating_system_disk_cache
    storage_account_type      = var.operating_system_disk_type
    write_accelerator_enabled = var.operating_system_disk_write_accelerator
  }

}

**Comment by jhisc** [comment]
Change has been merged in.
Version v1.3.0
