### ISSUE TITLE
Password has Unicode Chars that cause errors

### ISSUE THREAD

**Issue by riesbl01** [Azure-Terraform/terraform-azurerm-virtual-machine#9]
Just generated a VM and password was: k:Psj\u0026t#CC+\u003cMj%6j\u003c[*XXix55_g@3[x (Old password, no longer being used) and as you can see there is several Unicode letters in the password '\u003c' and '\u0026' so we need to remove chars from the password that cause this issue, specifically '>', '<', and '&'. Note that this is when using 'terraform output -json' which is how we are able to see sensitive values.

**Comment by riesbl01** [comment]
See PR: https://github.com/Azure-Terraform/terraform-azurerm-virtual-machine/pull/10

**Comment by jhisc** [comment]
Version v1.3.0
